### ISSUE TITLE
User Generator Error

### ISSUE THREAD

**Issue by tanismar** [robotology/kinect-wrapper#8]
Hi! 
I am trying to use the Kinect to try out 3D reconstruction algorithms before moving to the iCub and its stereoVision. I managed to make and compile kinect-wrapper without any error (on Ubuntu 15.04 with the OpenNI driver), but when running the KinectServer, I get the following output
Resolution RGB: 320x240
Resolution Depth: 320x240
User generator failed
Kinect failed to initialize
RFModule failed to open
And then the module closes and returns me to the command line. I have tried to find where the error comes from, but I have not been able to figure out if it is a driver problem, a code bug, or just a configuration issue. Any hint on what might be going on?
Thanks in advance!
Tanis

**Comment by dcam0050** [comment]
Hi @tanismar I have the same issue with the kinect-wrapper ... did you manage to find a way around it?

**Comment by Tobias-Fischer** [comment]
Which specific versions of OpenNI, NITE and SensorKinect are you using? It's very likely an issue of a version mismatch.

**Comment by dcam0050** [comment]
I have OpenNI2.2 and NITE2.2 installed in a home folder with their include and redist directories added to bashrc as per instructions and I have made sure that the installations are correct by running the test executables that come with the libraries.

Initially I tried installing the kinect as a yarp device by enabling OpenNI2DeviceClient but failed to get it listed as a yarpdev when issuing yarpdev --list. So I tried the kinect wrapper instead.

For that I downloaded and installed OpenNI1.5.4 in /usr to which I pointed at cmake time. NITE was not requested by the cmake.

I have a first generation Kinect and have installed libfreenect which runs without any issues when calling sudo freenect-glview.

Thank you for your help!

**Comment by dcam0050** [comment]
My final aim is to obtain the position for the kinect pixels with respect to the icub's left eye

**Comment by Tobias-Fischer** [comment]
Hi,

for `OpenNI2DeviceClient` I have no ideas what to do.
For `kinectWrapper`, you first need to uninstall your existing OpenNI (you have an incompatible version). Then, install `OpenNI` version Unstable-1.5.2.23 (mind the UNstable, you can get it from https://github.com/OpenNI/OpenNI/releases). Afterwards, you need to install `NITE-Bin-Dev-Linux-x64-v1.5.2.21` (from http://www.mira-project.org/downloads/3rdparty/bin-linux/), otherwise the skeleton tracker does not work (that might be your user generator error). Finally, install `SensorKinect-0.92-5.1.2.1` (from https://github.com/avin2/SensorKinect/releases).
Then, remove the build folder of `kinect-wrapper`, and run `ccmake` and `make` again.

Best, Tobias

**Comment by dcam0050** [comment]
Hi Tobias,

I followed your steps, uninstalled everything to start fresh and this time I am getting the following:

||| found /usr/local/share/ICUBcontrib/contexts/kinectServer/config.ini
Resolution RGB: 320x240
Resolution Depth: 320x240
Depth generator failed
Kinect failed to initialize
RFModule failed to open

instead of the user generator failing I get depth generator failed. Any ideas?

Thanks,
Daniel

**Comment by Tobias-Fischer** [comment]
Hi,
do the samples in `Redist/.../Samples/Bin/x64-Release/` work? Try `NiViewer` first, and `NiUserTracker` after. If not, do you have an Asus Xtion somewhere around to try? Did you also uninstall all Ubuntu openni packages? If you had some installed, unfortunately you have to uninstall everything again and start from scratch, sorry I should have mentioned this before ... Which Ubuntu do you use by the way?
Best, Tobias

**Comment by dcam0050** [comment]
I will try that ... I use Ubuntu 14.04

**Comment by dcam0050** [comment]
I also have freenect installed ... Does that affect the operation of kinect wrapper?

**Comment by tanismar** [comment]
Hi guys
Thanks for the instructions, Tobias. I installed the NITE and SensorKinect versions you described, although I left my OpenNI version as it was (libopenni-dev 1.5.4.0-9). Both KinectServer and KinectClientExample run without errors, although in the Client the viewer does not open. However, connecting directly the modules outputs to yarpviews, I can see that the output is working, although I am not sure if it is 100% correct: from /kinectServer/depth:o I get a sort of layered image (shown below), and the output from /kinectClientExample/depthPort:o seems frozen. I will try to remove openni and get the unstable version and try again. 
![screenshot from 2015-10-20 16 26 48](https://cloud.githubusercontent.com/assets/4818225/10610338/a8ced300-7747-11e5-97f4-f5c394406eeb.png)

**Comment by tanismar** [comment]
My mistake, I wasn't opening the application properly. Except for the skeleton (which I don't care much about), everything else works fine, as you can see below. This means too that we it is not necessary to fully reinstall openNI, as I have the apt-get repo version installed, which makes it much easier. 
Thanks a lot!!
![screenshot from 2015-10-20 16 41 02](https://cloud.githubusercontent.com/assets/4818225/10610825/d4804d06-7749-11e5-8a40-48c6ba1e05cf.png)

**Comment by tanismar** [comment]
Could that info be added to the README file somehow? I am sure it would greatly help future potential users. :)

**Comment by Tobias-Fischer** [comment]
Glad to hear it works for you! Could you please a few paragraphs for the readme file? Please post them here and I'll change the readme on the repository accordingly.

**Comment by Tobias-Fischer** [comment]
@dcam0050: Freenect should not affect kinect-wrapper.

**Comment by dcam0050** [comment]
I've been trying to recompile SensorKinect but it does not compile correctly when making CreateRedist because it complains that it is missing XnEventT.h I'm using version 0.92-5.1.2.1 for SensorKinect and I'm sure I checked out the unstable version even for OpenNI 1.5.2.23 .

I even tried the stable versions for both libraries and the more recent counterparts but still received the same error when trying to make SensorKinect CreateRedist and I made sure to manually delete anything related to openni in the computer as well to be sure there are no remnants from the last install. Any ideas?

Regarding an Asus Xtion, unfortunately there isn't one lying around right now. If there was could I use it without compiling SensorKinect?

Thanks for your help!

**Comment by Tobias-Fischer** [comment]
XnEvent.h is part of OpenNI .. did you run all the steps to install OpenNI as described in https://github.com/OpenNI/OpenNI/blob/master/README ?

**Comment by tanismar** [comment]
Hi Tobias, 
Maybe is enought to add the proper links and versions to the list of dependencies, something like this: 

Dependencies

YARP
icub-contrib-common
Kinect SDK and/or OpenNI 1.**X**
OpenCV
Cmaking the project
**NITE 1.X (available at http://www.mira-project.org/downloads/3rdparty/)**
               **(tested with NITE-Bin-Dev-Linux-x64-v1.5.2.21)**
**SensorKinect (available at https://github.com/avin2/SensorKinect/releases)**
**(tested with SensorKinect-0.92-5.1.2.1)

**Comment by Tobias-Fischer** [comment]
@tanismar Done!

**Comment by dcam0050** [comment]
Just succeeded in running kinect server! The issue is SensorKinect-0.92-5.1.2.1 was not compiling successfully with the manually installed OpenNI library. It only compiles when I do sudo apt-get install libopenni-dev which was v1.5.4.0-7 in my case.

After that I could successfully make the SensorKinect redist and kinect wrapper worked without a hitch.

Also for future reference for others, if you get an error saying that the sensor could not be found when trying to run the NiViewer example from the Openni redist double check that you have the unstable version of SensorKinect.

Thank you all for your help!

@Tobias-Fischer How would you suggest calibrating the kinect with respect to the icub's left eye?

**Comment by Tobias-Fischer** [comment]
Glad to hear it works. Does the skeleton tracking also work under this setup?

Regarding the calibration, see https://github.com/robotology/wysiwyd/issues/24

**Comment by dcam0050** [comment]
Yes skeleton tracking works like a charm as well when running the xml.

Thank you again!

**Comment by pattacini** [comment]
Thanks again @Tobias-Fischer for the help on this.
